[tool.poetry]
name = "filzl"
version = "0.1.0"
description = ""
authors = ["Pierce Freeman <pierce@freeman.vc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyterlab = "^4.0.11"
jupytext = "^1.16.1"
pydantic = "^2.5.3"
fastapi = "^0.109.0"
inflection = "^0.5.1"
click = "^8.1.7"
uvicorn = "^0.27.0"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "^7.4.4"
ruff = "^0.1.14"
types-setuptools = "^69.0.0.20240125"
maturin = "^1.4.0"
watchdog = "^3.0.0"
types-tqdm = "^4.66.0.20240106"

[build-system]
requires = ["maturin>=1.3.0"]
build-backend = "maturin"

#[tool.maturin]
#python-source = "python"

[tool.maturin]
bindings = "pyo3"
#module-name = "filzl._filzl"
features = ["pyo3/extension-module", "pyo3/generate-import-lib"]

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F", "I001"]
