[tool.poetry]
name = "filzl"
version = "0.1.0"
description = ""
authors = ["Pierce Freeman <pierce@freeman.vc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyterlab = "^4.0.11"
jupytext = "^1.16.1"
pydantic = "^2.5.3"
fastapi = "^0.109.0"
inflection = "^0.5.1"
click = "^8.1.7"
tqdm = "^4.66.1"
uvicorn = {extras = ["standard"], version = "^0.27.0.post1"}

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "^7.4.4"
ruff = "^0.1.14"
types-setuptools = "^69.0.0.20240125"
maturin = "^1.4.0"
watchdog = "^3.0.0"
types-tqdm = "^4.66.0.20240106"
pytest-asyncio = "^0.23.4"

[build-system]
requires = ["maturin>=1.3.0"]
build-backend = "maturin"

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true
plugins = [
  "pydantic.mypy"
]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Disable print statements
select = ["E4", "E7", "E9", "F", "I001", "T201"]
