[tool.poetry]
name = "filzl"
version = "0.1.0"
description = ""
authors = ["Pierce Freeman <piercefreeman@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyterlab = "^4.0.11"
jupytext = "^1.16.1"
pydantic = "^2.5.3"
fastapi = "^0.109.0"
inflection = "^0.5.1"
click = "^8.1.7"
uvicorn = "^0.27.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "^7.4.4"
ruff = "^0.1.14"

[tool.poetry.scripts]
runserver = "filzl.cli:runserver"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true
