version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: filzl_daemons
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: filzl_daemons_test_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
